services:
  backend:
    container_name: cakemanagerpd
    build: .
    ports:
      - 8080:8080
  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './prometheus.yml:/etc/prometheus/config.yml'