logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
spring:
  datasource:
    #initialization-mode: ALWAYS
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:./testdb
    #url=jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: true
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
#    default-schema: cake-manager
    change-log: classpath:/db/changelog/db.changelog-master.yaml

okta:
  oauth2:
    issuer: https://dev-47242716.okta.com/oauth2/default
    client-id: 0oa5aelqfzmqjujRp5d7
#    should be stored in secrets manager
    client-secret: 0vCNxH9qLdNVRe-UQosc2jsBwEwWihUzx_Tiq09d
    scopes: openid
#    redirect-uri: /authorization-code/callback

# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: ./uploads