spring:
  datasource:
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        type: info
        stat: debug
server:
  port: ${SERVER_PORT:8282}
