version: 2.1

orbs:
  maven: circleci/maven@1.1

build:
  docker:
     - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - run: java --version

workflows:
  maven_test:
    jobs:
      - maven/test
